import pyautogui, time
pyautogui.FAILSAFE = True
pyautogui.hotkey('ctrl', 'alt', 'w')
time.sleep(5.0)
pyautogui.moveTo(1912, 1189)
pyautogui.click()
print("请打开手机微信确认电脑版登录。")
login = input("是否登陆成功？(y/n)")
if login == "y":
    time.sleep(5.0)
    pyautogui.moveTo(1302, 522)
    pyautogui.click()
    pyautogui.press(['5', '0', '2'])
    time.sleep(5.0)
    pyautogui.moveTo(1378, 685)
    pyautogui.click()
    pyautogui.moveTo(1816, 1381)
    pyautogui.click()
    time.sleep(2.0)
    pyautogui.moveTo(1212, 823)
    pyautogui.scroll(-1000)
    pyautogui.moveTo(1232, 1027)
    pyautogui.click()
    pyautogui.moveTo(1648, 547)
    pyautogui.click()
    pyautogui.typewrite('E:\\covid19_data\\World\\')
    pyautogui.press('enter')
    pyautogui.moveTo(2068, 545)
    pyautogui.click()
    pyautogui.typewrite('修改日期：今天\n')
    pyautogui.moveTo(1515, 754)
    pyautogui.click()
    pyautogui.moveTo(1976, 1292)
    pyautogui.click()
    pyautogui.press('enter')

    pyautogui.moveTo(1816, 1381)
    pyautogui.click()
    time.sleep(2.0)
    pyautogui.moveTo(1212, 823)
    pyautogui.scroll(-1000)
    pyautogui.moveTo(1232, 1027)
    pyautogui.click()
    pyautogui.moveTo(1648, 547)
    pyautogui.click()
    pyautogui.typewrite('E:\\covid19_data\\Shanghai\\')
    pyautogui.press('enter')
    pyautogui.moveTo(2068, 545)
    pyautogui.click()
    pyautogui.typewrite('修改日期：今天\n')
    pyautogui.moveTo(1515, 754)
    pyautogui.click()
    pyautogui.moveTo(1976, 1292)
    pyautogui.click()
    pyautogui.press('enter')
    print("发送成功！")