import pyautogui, time
pyautogui.FAILSAFE = True
pyautogui.hotkey('ctrl', 'alt', 'w')
time.sleep(5.0)
pyautogui.moveTo(1912, 1189)
pyautogui.click()
print("请打开手机微信确认电脑版登录。")
login = input("是否登陆成功？(y/n)")
if login == "y":
    time.sleep(5.0)
    pyautogui.moveTo(1302, 522)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.typewrite('502') # 把这里的群换成你的群/联系人
    time.sleep(5.0)
    pyautogui.moveTo(1378, 685)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(1816, 1381)
    pyautogui.click()
    time.sleep(0.5)
    time.sleep(2.0)
    pyautogui.moveTo(1212, 823)
    time.sleep(0.5)
    pyautogui.scroll(-1000)
    time.sleep(0.5)
    pyautogui.moveTo(1232, 1027)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(1648, 547)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.typewrite('E:\\covid19_data\\World\\') # 把这里的路径换成前面一个文件里全球数据的存储位置
    time.sleep(0.5)
    pyautogui.press('enter')
    time.sleep(0.5)
    pyautogui.moveTo(2068, 545)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.typewrite('修改日期：今天\n')
    time.sleep(0.5)
    pyautogui.moveTo(1515, 754)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(1976, 1292)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.press('enter')
    time.sleep(0.5)

    pyautogui.moveTo(1816, 1381)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    time.sleep(2.0)
    pyautogui.moveTo(1212, 823)
    time.sleep(0.5)
    pyautogui.scroll(-1000)
    time.sleep(0.5)
    pyautogui.moveTo(1232, 1027)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(1648, 547)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.typewrite('E:\\covid19_data\\Shanghai\\') # 把这里的路径换成前面一个文件里上海数据的存储位置
    time.sleep(0.5)
    pyautogui.press('enter')
    time.sleep(0.5)
    pyautogui.moveTo(2068, 545)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.typewrite('修改日期：今天\n')
    time.sleep(0.5)
    pyautogui.moveTo(1515, 754)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.moveTo(1976, 1292)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.hotkey("alt", "s")
    time.sleep(0.5)
    print("发送成功！")
exit()